"""Run the H1 and H2 hunts directly on the JSON files, without Elasticsearch.

Same logic as the ES|QL queries in this folder. Use it to check results,
or as a fallback if the ELK lab will not start on your machine.

Usage:  python hunt_offline.py [../lab/data]  > ../results/hunt_results.md
"""
import collections
import json
import pathlib
import sys

DATA = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else pathlib.Path(__file__).parent.parent / "lab" / "data")

events = []
for f in sorted(DATA.glob("*.json")):
    for line in f.open(encoding="utf-8", errors="replace"):
        if line.strip():
            e = json.loads(line)
            e["dataset"] = f.stem
            events.append(e)

low = lambda v: (v or "").lower()
base = lambda p: (p or "").split("\\")[-1]


def table(title, header, rows):
    print(f"\n#### {title}\n")
    if not rows:
        print("_No results._")
        return
    print("| " + " | ".join(header) + " |")
    print("|" + "---|" * len(header))
    for r in rows:
        print("| " + " | ".join(str(c) for c in r) + " |")


proc = [e for e in events if e.get("EventID") == 1 and e.get("Image")]
print("# Hunt results (generated by hunt_offline.py)\n")
c = collections.Counter(e["dataset"] for e in events)
print("Events loaded: " + ", ".join(f"`{k}` {v}" for k, v in sorted(c.items())) + f" — **total {len(events)}**")

# ------------------------------------------------------------------ H1
print("\n## H1 — suspicious PowerShell (hypothesis-driven)")
ps = [e for e in proc if low(e["Image"]).endswith("powershell.exe")]
stack = collections.Counter((base(e.get("ParentImage")), e.get("User")) for e in ps)
table("H1.1 Who starts PowerShell (stack count, rare first)", ["ParentImage", "User", "executions"],
      [(p, u, n) for (p, u), n in sorted(stack.items(), key=lambda x: x[1])])

rows = []
for e in ps:
    cmd = low(e.get("CommandLine"))
    enc = " -enc" in cmd or "-encodedcommand" in cmd
    hid = "-w 1" in cmd or "-w hidden" in cmd or "-windowstyle hidden" in cmd
    if enc or hid:
        rows.append((e["@timestamp"], e["Hostname"], e.get("User"), base(e.get("ParentImage")),
                     len(e.get("CommandLine") or ""), enc, hid, "-nop" in cmd))
table("H1.2 Launcher flags", ["@timestamp", "Hostname", "User", "Parent", "cmd_len", "encoded", "hidden", "noprofile"], rows)

rows = []
for e in events:
    if e.get("EventID") == 4104:
        sb = low(e.get("ScriptBlockText"))
        web = any(t in sb for t in ("net.webclient", "downloaddata", "downloadstring"))
        dec = "frombase64string" in sb or "-bxor" in sb
        exe = "iex" in sb or "invoke-expression" in sb
        if web or dec:
            rows.append((e["@timestamp"], e["Hostname"], web, dec, exe, len(sb)))
table("H1.3 Script blocks with download/decode logic (EID 4104)",
      ["@timestamp", "Hostname", "web", "decode", "exec", "length"], rows)

kids = collections.Counter((e["Hostname"], e.get("User"), base(e["Image"]))
                           for e in proc if low(e.get("ParentImage")).endswith("powershell.exe"))
table("H1.4 Children of PowerShell", ["Hostname", "User", "Image", "n"],
      [(*k, n) for k, n in sorted(kids.items(), key=lambda x: x[1])])

rows = []
for e in events:
    if e.get("EventID") == 7045:
        p = low(e.get("ImagePath"))
        rows.append((e["@timestamp"], e["Hostname"], e.get("ServiceName"), e.get("StartType"),
                     e.get("AccountName"), "powershell" in p or "%comspec%" in p))
table("H1.5 New services (EID 7045)", ["@timestamp", "Hostname", "ServiceName", "StartType", "AccountName", "script_in_service"], rows)

c2 = collections.defaultdict(list)
for e in events:
    if e.get("EventID") == 3 and low(e.get("Image")).endswith("powershell.exe") and str(e.get("Initiated")) == "true":
        c2[(e["Hostname"], e.get("DestinationIp"), e.get("DestinationPort"))].append(e["@timestamp"])
table("H1.6 PowerShell outbound connections", ["Hostname", "DestinationIp", "DestinationPort", "connections", "first_seen"],
      [(*k, len(v), min(v)) for k, v in sorted(c2.items(), key=lambda x: min(x[1]))])

# ------------------------------------------------------------------ H2
print("\n## H2 — WannaCry TTPs (intel-driven)")
H = ("24D004A104D4D54034DBCFFC2A4B19A11F39008A575AA614EA04703480B1022C",
     "ED01EBFBC9EB5BBEA545AF4D01BF5F1071661840480439C6E5BABE8E080E41AA")
table("H2.1 WannaCry hashes", ["@timestamp", "Hostname", "Image"],
      [(e["@timestamp"], e["Hostname"], e["Image"]) for e in proc if any(h in (e.get("Hashes") or "").upper() for h in H)])
print(f"\n_Checked {sum(1 for e in proc if e.get('Hashes'))} process-creation events with hashes._")

table("H2.2 Kill-switch domain lookups", ["@timestamp", "Hostname", "QueryName"],
      [(e["@timestamp"], e["Hostname"], e.get("QueryName")) for e in events
       if e.get("EventID") == 22 and "iuqerfsodp9ifjaposdfjhgosurijfaewrwergwea" in low(e.get("QueryName"))])
print(f"\n_Checked {sum(1 for e in events if e.get('EventID') == 22)} DNS events._")

rows = []
for e in proc:
    img, cmd = low(e["Image"]), low(e.get("CommandLine"))
    if img.endswith(("vssadmin.exe", "wbadmin.exe", "bcdedit.exe")) or (img.endswith("wmic.exe") and "shadowcopy" in cmd):
        destr = "delete" in cmd or "recoveryenabled no" in cmd or "resize shadowstorage" in cmd
        rows.append((e["@timestamp"], e["Hostname"], e.get("User"), base(e.get("ParentImage")), e.get("CommandLine"), destr))
table("H2.3 Recovery tools (T1490)", ["@timestamp", "Hostname", "User", "Parent", "CommandLine", "destructive"], rows)

table("H2.4 icacls Everyone:F / attrib +h", ["@timestamp", "Hostname", "CommandLine"],
      [(e["@timestamp"], e["Hostname"], e.get("CommandLine")) for e in proc
       if (low(e["Image"]).endswith("icacls.exe") and "everyone:f" in low(e.get("CommandLine")))
       or (low(e["Image"]).endswith("attrib.exe") and "+h" in low(e.get("CommandLine")))])

table("H2.5 Services vs WannaCry pattern", ["@timestamp", "Hostname", "ServiceName", "wannacry_like"],
      [(e["@timestamp"], e["Hostname"], e.get("ServiceName"),
        e.get("ServiceName") == "mssecsvc2.0" or "-m security" in low(e.get("ImagePath")))
       for e in events if e.get("EventID") == 7045])

smb = collections.defaultdict(lambda: [0, set()])
for e in events:
    if e.get("EventID") == 3 and str(e.get("DestinationPort")) == "445" and str(e.get("Initiated")) == "true":
        k = (e["Hostname"], e.get("Image"))
        smb[k][0] += 1
        smb[k][1].add(e.get("DestinationIp"))
table("H2.6 Outbound SMB fan-out", ["Hostname", "Image", "connections", "targets"],
      [(h, i, n, len(t)) for (h, i), (n, t) in sorted(smb.items(), key=lambda x: -len(x[1][1]))])

# context for H2.3 triage: what else did the same user run around vssadmin?
print("\n#### H2.3 triage — commands by the same user on DC01\n")
for e in sorted((e for e in proc if "pandalab\\administrator" in low(e.get("User"))
                 and base(e.get("ParentImage")).lower() == "cmd.exe"), key=lambda e: e["@timestamp"]):
    print(f"- `{e['@timestamp']}` {base(e['Image'])}: `{e.get('CommandLine')}`")
print("\n#### H2.3 triage — files written on DC01 that look like AD database / registry hive copies (Sysmon 11)\n")
for e in events:
    if e.get("EventID") == 11 and any(t in low(e.get("TargetFilename")) for t in ("ntds.dit", "system_hive")):
        print(f"- `{e['@timestamp']}` {base(e.get('Image'))} wrote `{e.get('TargetFilename')}`")
